PREFIX c: <urn:circuit:>
CONSTRUCT {
  ?t a c:Times ; c:in ?a0 ; c:in ?a1 ; c:feeds ?ans .
  ?ans a c:Plus ; c:answer ?anskey .
}
WHERE {
	?a0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#subject> ?x . 
	?a0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> <urn:d:e> . 
	?a0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> ?y . 
	?a1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#subject> ?y . 
	?a1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate> <urn:d:e> . 
	?a1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#object> ?z . 
  BIND(SHA256(STR(?a0)) AS ?srt0)
  BIND(SHA256(STR(?a1)) AS ?srt1)
  BIND(IF(?srt0 <= ?srt1, ?srt0, ?srt1) AS ?srt2)
  BIND(IF(?srt0 <= ?srt1, ?srt1, ?srt0) AS ?srt3)
  BIND(CONCAT("A", "|x=", STR(?x), "|z=", STR(?z)) AS ?anskey)
  BIND(IRI(CONCAT("urn:g:t:", SHA256(CONCAT("T", "|", ?srt2, "|", ?srt3)))) AS ?t)
  BIND(IRI(CONCAT("urn:g:a:", SHA256(?anskey))) AS ?ans)
}

