PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX sorg: <http://schema.org/>
SELECT ?u ?prod ?rev WHERE { ?u wsdbm:makesPurchase ?p . ?p wsdbm:purchaseFor ?prod . ?prod rev:hasReview ?rev . }
