PREFIX wsdbm: <http://db.uwaterloo.ca/~galuc/wsdbm/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX sorg: <http://schema.org/>
SELECT ?u WHERE { ?u wsdbm:likes ?a . ?u wsdbm:subscribes ?b . ?u wsdbm:makesPurchase ?c . }
